### ISSUE TITLE
Word2Vec - potential issues

### ISSUE THREAD

**Issue by benchiverton** [benchiverton/GingerbreadAI#18]
Parent for all potential issues with the Word2Vec library

**Comment by chipolatas** [comment]
https://github.com/chipolatas/NeuralNetwork/blob/03affd72bef12301684ea824c9c9a139a3f6bb0a/AI/NLP/Word2Vec/Word2Vec.cs#L172

Shouldn't the logic here be instead:
```
(_fileHandler.FileSize * id) / _numberOfThreads
```

**Comment by chipolatas** [comment]
The last line is never read, as it has finished reading the file when the last line is read (ie - reader.EndOfStream = true) which is consumes in the following logic.

Can be fixed by having a new line at EOF

**Comment by benchiverton** [comment]
Issues fixed in https://github.com/benchiverton/GingerbreadAI/pull/44
